### ISSUE TITLE
I don't know if you can?

### ISSUE THREAD

**Issue by gallegonovato** [Laicure/hosts#6]
Good afternoon:

First of all let me thank you for your work, your help and your time.

I would like to ask you a question, if I may. 

I don't know if it would be possible to upload the file created by Hostz to your github. I mean the one you put in https://github.com/Laicure/hosts and more specifically https://bitbucket.org/Laicure/public/downloads/hosts ( https://github.com/Laicure/hosts#custom-hosts-files-sources-direct-download ).

I wanted to use the host in Adaway. And this application works better with host url.

Receive a warm hug and thank you for your time and help.

**Comment by Laicure** [comment]
Yes, sure.
Thanks for the suggestion.
At least, we have two mirrors instead of one but we would have a lot of commits though it's ok as it is only weekly. ;)
Commit: 0d62ada

**Comment by gallegonovato** [comment]
> Yes, sure.
> Thanks for the suggestion.
> At least, we have two mirrors instead of one but we would have a lot of commits though it's ok as it is only weekly. ;)
> Commit: [0d62ada](https://github.com/Laicure/hosts/commit/0d62ada6dbecc4c4d479fc56d17cac529a3b0c35)

Good morning @Laicure 

Thank you very much for your help, time and understanding. So we have more fan thanks to you. And since I had that host, which was created at https://github.com/Laicure/hosts#custom-hosts-files-sources-direct-download for Windows fine, but to use Adaway as it was more fuss. And since I had that potential, I came up with the idea. I don't know what you think of these host lists: 

https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-8-0.2190753/post-85618677 

https://urlhaus.abuse.ch/downloads/hostfile/ 

https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-8-0.2190753/page-819#post-85559583 

https://gitlab.com/Jorgu81/hosts/-/raw/master/Google/HostsGoogle 

https://gitlab.com/Jorgu81/hosts/-/raw/master/Mozilla/Mozilla 

https://gitlab.com/Jorgu81/hosts/-/raw/master/Router/Blocklist 

https://gitlab.com/Jorgu81/hosts/-/raw/master/Router/Router 

https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts 

https://hosts.oisd.nl/ or https://hosts.oisd.nl/basic/

 A hug and a thousand thanks for all your help and time.

**Comment by Laicure** [comment]
oh thanks!
I will look into those each and reply here ;)
Thanks for checking those.

My criteria for adding sources are:
- almost everything @StevenBlack has
- updated, at least, every month
- very few blocking issues
- only pop-ups/ads, trackers, and malware/security/cryptominers
- possibly does not break any app functionality

**Comment by Laicure** [comment]
```
https://urlhaus.abuse.ch/downloads/hostfile/
```
\> already in the sources <br><br>
```
https://gitlab.com/Jorgu81/hosts/-/raw/master/Google/HostsGoogle
https://gitlab.com/Jorgu81/hosts/-/raw/master/Mozilla/Mozilla
https://gitlab.com/Jorgu81/hosts/-/raw/master/Router/Blocklist
https://gitlab.com/Jorgu81/hosts/-/raw/master/Router/Router
```
\> these will break a lot of things <br><br>

```
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
```
\> add this manually if you like, this is an extension for fakenews, gambling, porn, and social... those are preference-specific that's why I am not adding those on the default list <br><br>

```
https://hosts.oisd.nl/
```
\> I only take _direct_ sources, that list contains the sources from [here](https://oisd.nl/includedlists) <br><br>

```
https://github.com/jerryn70/GoodbyeAds
```
\> too many issues

**Comment by gallegonovato** [comment]
Good Aftenoon: Thank you very much for your help and time. I'm glad I was helpful. A hug and a thousand thanks for your time and help

**Comment by Laicure** [comment]
I tried using the hosts file link from bitbucket using adaway, it works well. so I will be removing the mirror here.

**Comment by gallegonovato** [comment]
Good afternoon @Laicure

First of all thank you for your time and help.

I would like to ask you if there is a possibility that the host created https://github.com/Laicure/hosts#custom-hosts-files-sources-direct-download (by your HostsZ application). It could be added to your online host: https://raw.githubusercontent.com/Laicure/hosts/master/shithosts

In order to have a better protection. And to be able to use the host generated by HostsZ (in https://github.com/Laicure/hosts#custom-hosts-files-sources-direct-download) can be added to host applications. Since for example in Adaway you always have to download the file and add it when there are updates. And so if it was attached to your shithosts host it would be a great help.

I am sorry for the inconvenience caused, and I beg your pardon if I have offended you in any way or if I have done something wrong. It was not and is not my intention.

Receive a warm embrace

**Comment by Laicure** [comment]
oh hey, no worries.

May you show me the error where bitbucket link fails? We might push the issue to the AdAway team.
