### ISSUE TITLE
Host source suggestion?

### ISSUE THREAD

**Issue by gallegonovato** [Laicure/hosts#8]
good afternoon @Laicure 

for example an interesting host list for their sources I see 

https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt.

https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/hosts.txt

https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/hosts.txt

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/fake-domains.txt

https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt

https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

https://github.com/migueldemoura/ublock-umatrix-rulesets/tree/master/Hosts

could be used at https://raw.githubusercontent.com/Laicure/hosts/master/shithosts or https://raw.githubusercontent.com/Laicure/hosts/master/hosts

 I don't know what it looks like to you?. 

 a hug and thank you very much for your help and time

**Comment by Laicure** [comment]
Thanks, I will be checking those once I'm available.

**Comment by gallegonovato** [comment]
Good afternoon:

I don't know if it can help you or what you think:

https://gitlab.com/AuroraOSS/AppWarden/-/raw/master/hosts/warden_trackers.txt

https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt

https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt

https://v.firebog.net/hosts/Airelle-trc.txt

https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

https://hostfiles.frogeye.fr/multiparty-only-trackers-hosts.txt

https://infinitytec.github.io/blocklists/blocklists.html

https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt

Best regards and sorry for the inconvenience. And I hope they will be useful to add to the host.

**Comment by Laicure** [comment]
oh that's a lot, you can ask[ StevenBlack](https://github.com/StevenBlack/hosts) for his comments too.
We should keep our list, at least, to the minimum but updated and personally curated.

**Comment by Laicure** [comment]
This one is good, I will be checking the sources this weekend.
https://github.com/hectorm/hblock/blob/master/SOURCES.md
